### ISSUE TITLE
Fix issue: syntax error on conditionals (While and If)

### ISSUE THREAD

**Issue by hmathieu-insat** [hmathieu-insat/4A-Compiler#2]
```
        // TODO Fix issue: syntax error on 2 following brackets.
```

https://github.com/hmathieu-insat/4A-Compiler/blob/78684d06385979178dfcd4f60d4b9151171986cd/tests/tests_ok/test_WithScopes.c#L12

**Comment by Ger0th** [comment]
Compiler was waiting for a semicolon after if or while. Now only awaits semicolon after expr.
